### ISSUE TITLE
Argument of type 'this' is not assignable to parameter of type 'Construct'.

### ISSUE THREAD

**Issue by moltar** [awslabs/aws-bootstrap-kit#102]
It looks like the `constructs` packages is outdated and I am getting the type conflicts with the latest version.

My project:

```
    "constructs": "10.1.28",
```

> Argument of type 'this' is not assignable to parameter of type 'Construct'.

```
Argument of type 'this' is not assignable to parameter of type 'Construct'.
  Type 'AWSBootstrapKitLandingZoneStage' is not assignable to type 'Construct'.
    Types of property 'node' are incompatible.
      Type 'import(".../node_modules/constructs/lib/construct").Node' is not assignable to type 'import(".../node_modules/aws-bootstrap-kit/node_modules/constructs/lib/construct").Node'.
        Types have separate declarations of a private property 'host'.
```

**Comment by flochaz** [comment]
That is weird, you should be able to use whatever version since we added `^` in peer deps: https://github.com/awslabs/aws-bootstrap-kit/pull/77/files

**Comment by moltar** [comment]
Wait, the `dependencies` value is still fixed though!

https://github.com/awslabs/aws-bootstrap-kit/blob/cfaf3f699bb76d29d31311b2f72307866352a92e/source/aws-bootstrap-kit/package.json#L58-L65

**Comment by flochaz** [comment]
You can solve this by adding the following block to your package.json : 
```json
"overrides": {
      "aws-bootstrap-kit": {
        "aws-cdk-lib": "2.27.0",
        "constructs": "10.1.31"
      }
    }
 ```

**Comment by moltar** [comment]
Ok, this worked. But this requires `npm@8`. This may not affect many people, but still good to know.

Another pro tip, it is possible to use references to the package versions you already have installed:


```json
  "overrides": {
    "aws-cdk-lib": "$aws-cdk-lib",
    "constructs": "$constructs"
  }
```
