### ISSUE TITLE
`cdk-sso-sync` repo link is broken

### ISSUE THREAD

**Issue by moltar** [awslabs/aws-bootstrap-kit#108]
https://github.com/awslabs/aws-bootstrap-kit/blob/f4167dd050ce6fd687450e0da8abf81c769ebac3/source/cdk-sso-sync/package.json#L13

Actual link: `https://github.com/awslabs/aws-bootstrap-kit/tree/main/source/cdk-sso-sync`

**Comment by flochaz** [comment]
Will fix and follow up with a new PR to remove the need for this utils since it has finally been fixed by cdk https://github.com/aws/aws-cdk/pull/19454 ...

**Comment by moltar** [comment]
Yes, good point, wasn't sure if it targets the same functionality. I just tried searching NPM, found this package, and then saw the link being broken.
