### ISSUE TITLE
Defining account types

### ISSUE THREAD

**Issue by moltar** [awslabs/aws-bootstrap-kit#112]
Would be great to get some docs and definitions of the different account types. Some are self explanatory.

But what is "DNS" type for?

What does "Playground" mean? Is it the same as "Sandbox" aka "Dev"?

**Comment by flochaz** [comment]
is https://github.com/awslabs/aws-bootstrap-kit/pull/114 clear enough ?

**Comment by moltar** [comment]
Left comments on the PR
