### ISSUE TITLE
Offer a Python version of the Bootstrap Kit

### ISSUE THREAD

**Issue by npvisual** [awslabs/aws-bootstrap-kit#119]
## Description

One of the really nice features of the CDK is that it supports different languages to describe your AWS infrastructure (Typescript, Javascript, Python, etc.). Most of our current _infrastructure-as-code_ has been written using the AWS CDK in Python.

While porting this to Typescript would be do-able (not desired though!), it would be good to be able to leverage existing code in Python to support migrating to one AWS account per "context" (tenant, person, envt type etc.)

**Comment by flochaz** [comment]
python is supported : https://pypi.org/project/aws-ssabuilders.aws-bootstrap-kit/
