### ISSUE TITLE
feat: Make root HostedZone accessible

### ISSUE THREAD

**Issue by ntippie** [awslabs/aws-bootstrap-kit#89]
# Problem Statement

I am making a CDK app to manage an organization's infrastructure. The organization's domain name is used for multiple purposes, including the SDLC, the organization's email service, and domain ownership verification for external services. I am looking to add MX and other records to the root `HostedZone`. Unfortunately it is created by `AwsOrganizationStack` but is not accessible for other stacks.

I would like to be able to either/both:
- Provide a `HostedZone` via `AwsOrganizationStackProps`
- Access the `HostedZone` created by `AwsOrganizationStack` (created via `RootDns`)

As a workaround, I attempted to prevent `AwsOrganization` from creating a `RootDns` and intended to define my own `RootDns`, but `RootDnsProps` requires `stagesAccounts` which is also not accessible from `AwsOrganization`.

**Comment by flochaz** [comment]
Good point. will give both options.

**Comment by ntippie** [comment]
Included in 0.7.0. Thank you!
